[tool.ruff]
target-version = "py38"

[tool.ruff.lint]
ignore = [
    "D203",
    "D213",
    "ANN101",
    "D107",
    "T201",
    "TD",
    "FIX001",
    "FIX002",
    "PYI024", # false positives in lib/deejayit.py
    # because we are using ruff format...
    "COM812",
    "ISC001",
]
select = ["ALL"]

[tool.ruff.lint.pydocstyle]
convention = "pep257"

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.per-file-ignores]
"tests/*" = [
    "ANN201", # it is always None for tests
    "D100",   # each test is documented
    "INP001", # is it not how pytest works?
    "S101",   # pytest works this way
]

[tool.coverage]

[tool.coverage.run]
branch = true
omit = ["./tests/*"]
[tool.coverage.report]
# Regexes for lines to exclude from consideration
exclude_also = [
    # Don't complain about missing debug-only code:
    "def __repr__",
    "if self\\.debug",

    # Don't complain if tests don't hit defensive assertion code:
    "raise AssertionError",
    "raise NotImplementedError",

    # Don't complain if non-runnable code isn't run:
    "if 0:",
    "if __name__ == .__main__.:",

    # Don't complain about abstract methods, they aren't run:
    "@(abc\\.)?abstractmethod",
]

ignore_errors = true
show_missing = true
skip_empty = true

[tool.coverage.html]
directory = "coverage_html_report"
